prefix: "!"

levels:
  "1175809853332148376": 400  # ã‚µãƒ¼ãƒãƒ¼ã‚ªãƒ¼ãƒŠãƒ¼
  "1175782164592349214": 300  # ãƒ¢ãƒ‡ãƒ¬ãƒ¼ã‚¿ãƒ¼ãƒªãƒ¼ãƒ€ãƒ¼
  "1141650594105393152": 200  # ãƒ¢ãƒ‡ãƒ¬ãƒ¼ã‚¿ãƒ¼ï¼ˆãƒ•ã‚£ãƒ«ã‚¿ãƒ¼ãƒã‚¤ãƒ‘ã‚¹ã‚ã‚Šï¼‰
  "1175782074918129674": 100  # ãƒˆãƒ©ã‚¤ã‚¢ãƒ«ãƒ¢ãƒ‡ãƒ¬ãƒ¼ã‚¿ãƒ¼
  "1122092896594710599": 100  # botãƒ­ãƒ¼ãƒ«

plugins:

  automod:
    enabled: true
    bypass_level: 200
    triggers:
      blacklistedWords:
        enabled: true
        words:
          - "faggot"
          - "f4ggot"
          - "nigger"
          - "n1gger"
          - "ni99er"
          - "niga"
          - "retard"
          - "r3tard"
          - "tard"
          - "tranny"
    actions:
      warn:
        enabled: true
        reason: "ç¦æ­¢ãƒ¯ãƒ¼ãƒ‰ã®ä½¿ç”¨"
      mute:
        enabled: true
      ban:
        enabled: true
    settings:
      escalation:
        - warns: 3
          action: mute
          duration: "1d"
          reason: ":warning: è­¦å‘Š 3 ä»¶: 1 æ—¥ã®ãƒŸãƒ¥ãƒ¼ãƒˆã€‚"
        - warns: 4
          action: mute
          duration: "2d"
          reason: ":warning: è­¦å‘Š 4 ä»¶: 2 æ—¥ã®ãƒŸãƒ¥ãƒ¼ãƒˆã€‚"
        - warns: 5
          action: mute
          duration: "3d"
          reason: ":warning: è­¦å‘Š 5 ä»¶: 3 æ—¥ã®ãƒŸãƒ¥ãƒ¼ãƒˆã€‚"
        - warns: 6
          action: mute
          duration: "7d"
          reason: ":hourglass_flowing_sand: è­¦å‘Š 6 ä»¶: 1 é€±é–“ã®ãƒŸãƒ¥ãƒ¼ãƒˆã€‚"
        - warns: 7
          action: ban
          duration: 3
          reason: ":no_entry_sign: è­¦å‘Š 7 ä»¶: 3 æ—¥é–“ã®ä¸€æ™‚BANã€‚"
        - warns: 8
          action: ban
          duration: 8
          reason: ":no_entry_sign: è­¦å‘Š 8 ä»¶: 8 æ—¥é–“ã®ä¸€æ™‚BANã€‚"
        - warns: 10
          action: ban
          duration: 0
          reason: ":lock: è­¦å‘Š 10 ä»¶: æ°¸ä¹…BANã€‚ç•°è­°ç”³ã—ç«‹ã¦å¯èƒ½ã€‚"

  auto_reactions:
    enabled: true
    can_manage: true
    rules:
      - pattern: "(?i)\\bgay\\b"
        reactions:
          - regional_indicator_g
          - regional_indicator_a
          - regional_indicator_y

  mod_actions:
    enabled: true
    log_channel_id: "1288068409157750806"
    case_auto_close_days: 30
    mod_roles:
      - "1175782164592349214"
      - "1141650594105393152"
      - "1175782074918129674"
      - "1122092896594710599"
    punishments:
      warn:
        enabled: true
        max_warns: 3
      mute:
        enabled: true
        duration: "10åˆ†"
      kick:
        enabled: true
        reason: "ãƒ«ãƒ¼ãƒ«é•åã«ã‚ˆã‚‹ã‚­ãƒƒã‚¯"
      ban:
        enabled: true
        reason: "ãƒ«ãƒ¼ãƒ«é•åã«ã‚ˆã‚‹ãƒãƒ³"
        duration: 0
      auto_escalate:
        enabled: true
    dm_on_warn: true
    dm_on_kick: true
    dm_on_ban: true
    message_on_warn: true
    message_on_kick: true
    message_on_ban: true
    message_channel: null
    warn_message: '{guildName}ã‚µãƒ¼ãƒãƒ¼ã§è­¦å‘Šã‚’å—ã‘ã¾ã—ãŸ: {reason}'
    kick_message: '{guildName}ã‚µãƒ¼ãƒãƒ¼ã‹ã‚‰ã‚­ãƒƒã‚¯ã•ã‚Œã¾ã—ãŸã€‚ç†ç”±: {reason}'
    ban_message: '{guildName}ã‚µãƒ¼ãƒãƒ¼ã‹ã‚‰ãƒãƒ³ã•ã‚Œã¾ã—ãŸã€‚ç†ç”±: {reason}'
    tempban_message: '{guildName}ã‚µãƒ¼ãƒãƒ¼ã‹ã‚‰{banTime}é–“ãƒãƒ³ã•ã‚Œã¾ã—ãŸã€‚ç†ç”±: {reason}'
    alert_on_rejoin: true
    alert_channel: "1288068409157750806"
    warn_notify_enabled: true
    warn_notify_threshold: 5
    warn_notify_message: |-
      ã“ã®ãƒ¦ãƒ¼ã‚¶ãƒ¼ã¯ã™ã§ã«**{priorWarnings}**ä»¶ã®è­¦å‘Šã‚’æŒã£ã¦ã„ã¾ã™ï¼
      éå»ã®ã‚±ãƒ¼ã‚¹ã‚’ç¢ºèªã—ã€è­¦å‘Šã‚’ç¶šã‘ã‚‹ã‹åˆ¤æ–­ã—ã¦ãã ã•ã„ã€‚
      è­¦å‘Šã‚’ç™ºè¡Œã—ã¾ã™ã‹ï¼Ÿ
    ban_delete_message_days: 1
    attachment_link_reaction: warn
    can_note: true
    can_warn: true
    can_mute: true
    can_kick: true
    can_ban: true
    can_unban: true
    can_view: true
    can_addcase: true
    can_massunban: true
    can_massban: true
    can_massmute: true
    can_hidecase: true
    can_deletecase: true
    can_act_as_other: true
    create_cases_for_manual_actions: true

  mutes:
    enabled: true
    default_duration: "10åˆ†"
    notify_channel_id: "1288068409157750806"
    log_channel_id: "1288068409157750806"
    muted_role_id: "1287679657780449367"

  utility:
    can_roles: true
    can_level: true
    can_search: true
    can_clean: true
    can_info: true
    can_server: true
    can_inviteinfo: true
    can_channelinfo: true
    can_messageinfo: true
    can_userinfo: true
    can_roleinfo: true
    can_emojiinfo: true
    can_snowflake: true
    can_reload_guild: true
    can_nickname: true
    can_ping: true
    can_source: true
    can_vcmove: true
    can_vckick: true
    can_help: true
    can_about: true
    can_context: true
    can_jumbo: true
    can_avatar: true
    info_on_single_result: true
    autojoin_threads: true
    jumbo_size: 128

  welcome_message:
    enabled: true
    channel_id: null
    message: null
    mention: false
    image_enabled: false
    image_url: null
    dm_enabled: true
    dm_message: |
      ğŸ‰{user}ã•ã‚“ã€{guild}ã¸ã‚ˆã†ã“ãï¼

      ã‚µãƒ¼ãƒãƒ¼ã‚’ã”åˆ©ç”¨ã„ãŸã ãå‰ã«ã€ã¾ãšã¯ ğŸ“œ [ãƒ«ãƒ¼ãƒ«](https://discord.com/channels/1122080011822825475/1122083465895100516) ã‚’ã”ç¢ºèªãã ã•ã„ã€‚çš†ã•ã¾ãŒå¿«é©ã«éã”ã›ã‚‹ç’°å¢ƒã‚’æ•´ãˆã‚‹ãŸã‚ã€å¿…ãšã”ä¸€èª­ãã ã•ã„ã€‚

      ğŸ“¢ æœ€æ–°æƒ…å ±ã‚„å‘ŠçŸ¥ã¯ [ã“ã¡ã‚‰](https://discord.com/channels/1122080011822825475/1124285854890856458) ã‚’ã”ç¢ºèªãã ã•ã„ã€‚

      ğŸ›¡ï¸ èªè¨¼æ‰‹ç¶šãï¼š
      - ğŸ”— [èªè¨¼ãƒãƒ£ãƒ³ãƒãƒ«](https://discord.com/channels/1122080011822825475/1122090258897580082)
      - ğŸ’» [PCç‰ˆã‚¬ã‚¤ãƒ‰](https://www.youtube.com/watch?v=SbDltmom1R8)
